HOUSEHOLD_TYPE = "small_family"
PERSONS = 3
WEALTH_LEVEL = "middle"
WEALTH_FACTOR = 1.0

BATTERY_CAPACITY = 13.5 # kWh
ROUND_TRIP_EFFICIENCY = 0.9
BATTERY_MIN_SOC_FRACTION = 0.05

SOLAR_PANEL_CAPACITY = 5.0 # kW
MAX_INVERTER_OUTPUT = 4.0  # kW

BASE_LOAD = 0.4
PEAK_LOAD = 4.5
VARIABILITY_LOAD = 1.0

GRID_EXPORT_LIMIT = 20 # kW
EXPORTED_ENERGY_COST = 0.009  # $/kWh
IMPORTED_ENERGY_COST = 0.0075 # $/kWh

INVERTER_FAILURE_FREQUENCY = 0.05
INVERTER_FAILURE_DURATION = 36 # hours

MONTH_LENGTH_DAYS = 30

SIMULATION_DURATION = 30
TIMESTEP = 60  # minutes
SEASON = "winter" # "spring" | "summer" | "autumn" | "winter"
MANAGEMENT_STRATEGY = "charge_priority" # "load_priority" | "charge_priority" | "produce_priority"