BATTERY_CAPACITY = 13.5 #Kwh
ROUND_TRIP_EFFICIENCY = 0.9 
BATTERY_MIN_SOC_FRACTION = 0.05

SOLAR_PANEL_CAPACITY = 5 #kw
MAX_INVERTER_OUTPUT = 4 #kw

BASE_LOAD = 0.5
PEAK_LOAD = 3.5
VARIABILITY_LOAD = 1.1

GRID_EXPORT_LIMIT = 20 #kw
EXPORTED_ENERGY_COST = 0.009 # $/kWh  cents
IMPORTED_ENERGY_COST = 0.0075 # $/kWh  cents

INVERTER_FAILURE_FREQUENCY = 0.05
INVERTER_FAILURE_DURATION = 36 # In hours

MONTH_LENGTH_DAYS = 30

SIMULATION_DURATION = 30
TIMESTEP = 60  #En minutos
SEASON = "winter" # "spring" | "summer" | "autumn" | "winter"
MANAGEMENT_STRATEGY = "charge_priority" # "load_priority" | "charge_priority" | "produce_priority"