HOUSEHOLD_TYPE = "large_family"
PERSONS = 5
WEALTH_LEVEL = "high"
WEALTH_FACTOR = 1.2

BATTERY_CAPACITY = 20.0 # kWh
ROUND_TRIP_EFFICIENCY = 0.9
BATTERY_MIN_SOC_FRACTION = 0.05

SOLAR_PANEL_CAPACITY = 8.0 # kW
MAX_INVERTER_OUTPUT = 6.0  # kW

BASE_LOAD = 0.8
PEAK_LOAD = 7.0
VARIABILITY_LOAD = 1.3

GRID_EXPORT_LIMIT = 20 # kW
EXPORTED_ENERGY_COST = 0.009  # $/kWh
IMPORTED_ENERGY_COST = 0.0075 # $/kWh

INVERTER_FAILURE_FREQUENCY = 0.05
INVERTER_FAILURE_DURATION = 36 # hours

MONTH_LENGTH_DAYS = 30

SIMULATION_DURATION = 30
TIMESTEP = 60  # minutes
SEASON = "winter" # "spring" | "summer" | "autumn" | "winter"
MANAGEMENT_STRATEGY = "charge_priority" # "load_priority" | "charge_priority" | "produce_priority"